[slurmise]
base_dir = "."

[slurmise.job.perfectScaler]
job_spec = "--intensity {intensity} --duration {duration}"
default_time = 234
[slurmise.job.perfectScaler.variables]
intensity = {type = "numeric"}
duration = {type = "numeric"}
