name: Test slurmise

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }} --group dev

      - name: Run tests
        run: |
          uv run task test

      - name: Run linter
        run: uv run task fmt-check

      - name: Upload coverage report
        run: uv run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
