name: Test slurmise

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install hatch

      - name: Install dependencies
        run: hatch env create test

      - name: Run tests
        run: |
          hatch run test:test -- --cov --random-order --cov-append --cov-report=json
          ls -alh

      - name: Run linter
        run: hatch fmt --check --linter

      - name: Upload coverage report
        uses: coverallsapp/github-action@v2
        with:
          debug: true
          allow-empty: true
          file: .coverage
